### ISSUE TITLE
ch03/pretrain_inception_v3_cifar10_with_aug.pyのCIFAR10Dataset.upscale()でメモリを異常に消費する問題

### ISSUE THREAD

**Issue by masakiaota** [oreilly-japan/deep-learning-with-keras-ja#3]
表題の通りclass CIFAR10Dataset():において、
```
    def upscale(self, x, data_size):
        # ゼロ行列がすごいメモリを食う
        data_upscaled = np.zeros((data_size,
                                  self.image_shape[0],
                                  self.image_shape[1],
                                  self.image_shape[2]))
```
おそらくこの部分が原因でメモリを非常に消費します。
RAM64GBのUbuntuで試してみたところ少なくとも40GBは消費していました(ここでctrl-Cしました)

READMEの環境でこれは動作したのでしょうか？

**Comment by SnowMasaya** [comment]
ご指摘ありがとうございます。
こちらのコードは書籍では解説していないコードになります。
指定環境ではデータサイズを小さくして動作確認しました。下記のコミットが反映内容です。

https://github.com/oreilly-japan/deep-learning-with-keras-ja/commit/4aab7f9b93d412c5f81684f0a3fbf8305fdb4350

画像のサイズを変更しても対応可能です。
下記の行で画像のサイズを調整しています。

https://github.com/oreilly-japan/deep-learning-with-keras-ja/blob/4c10d3a03fd2eeffeac6f6c650bd289d674abf25/ch03/pretrain_inception_v3_cifar10_with_aug.py#L35

cifar10では32x32の画像サイズですがInception-v3は(150, 150, 3)のサイズが必要となっているためこの処理をいれています。

https://keras.io/applications/#inceptionv3

**Comment by masakiaota** [comment]
お返事ありがとうございます。

本の内容がすごくスラスラ読みやすくて、読者として素人ながら良い訳だと感じました。素敵な本を素敵に訳してくださって改めて感謝申し上げます。ありがとうございます。
