### ISSUE TITLE
AdversarialModelで「AttributeError: 'AdversarialModel' object has no attribute '_feed_output_shapes'」が発生する。

### ISSUE THREAD

**Issue by sinjorjob** [oreilly-japan/deep-learning-with-keras-ja#5]
P１５５以降でAdversarialModelを使ったGANの生成コードを実行すると、以下のエラーが発生します。

AttributeError: 'AdversarialModel' object has no attribute '_feed_output_shapes'

kerasのバージョンは書籍の通り2.1.2にしています。

**Comment by SnowMasaya** [comment]
ご指摘ありがとうございます。

下記のOS、pythonのバージョン、環境構築、実行コードで確認しましたがエラーが再現できませんでした。

解決できるか分かりませんがお手数ですがOS、pythonのバージョン、環境構築、実行コード、エラーの全メッセージを教えて頂けないでしょうか。

- OS
  - macOS High Sierra
- pythonのバージョン
  - 3.6.0

- 環境構築

`pyenv`でpython3.6.0のインストール済み

```
virtualenv --python=/Users/masayaoogushi/.pyenv/shims/python3 ch04_py
source ch04_py/bin/activate
pip install git+https://github.com/bstriner/keras-adversarial.git
pip install -r requirements.txt
```

実行コード

```
python example_gan_convolutional.py
```

**Comment by sinjorjob** [comment]
ご回答ありがとうございます。

以下エラーが発生する環境の詳細情報です。

OS:Windows10
Python:3.6.3 (minicondaを使って導入しています）
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝－
git clone https://github.com/oreilly-japan/deep-learning-with-keras-ja.git　でダウンロード済み。
なお、以下のエラーが発生するのはJupterNotebook上でexample_gan_convolutional.pyのソースをすべてコピペして実行した場合に発生します。

AttributeError: 'AdversarialModel' object has no attribute '_feed_output_shapes'

エラー内容は以下の通りです（パスは一部マスクしています）
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-e930c9b02c5b> in <module>()
    129     history = model.fit(x=xtrain, y=y, validation_data=(xtest, ytest), 
    130                         callbacks=[generator_cb], epochs=100,
--> 131                         batch_size=32)
    132     df = pd.DataFrame(history.history)
    133     df.to_csv("output/gan_convolutional/history.csv")

c:\users\xxx\miniconda3\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1579             class_weight=class_weight,
   1580             check_batch_axis=False,
-> 1581             batch_size=batch_size)
   1582         # Prepare validation data.
   1583         do_validation = False

c:\users\xxx\miniconda3\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1397 
   1398         output_shapes = []
-> 1399         for output_shape, loss_fn in zip(self._feed_output_shapes, self._feed_loss_fns):
   1400             if loss_fn is losses.sparse_categorical_crossentropy:
   1401                 output_shapes.append(output_shape[:-1] + (1,))

AttributeError: 'AdversarialModel' object has no attribute '_feed_output_shapes'
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
また、DOS上で「python example_gan_convolutional.py」を実行した場合は以下のエラーが発生しました。

C:\Users\xxx\ML\tyokan_deep\ch04>python example_gan_convolutional.py
C:\Users\xxx\Miniconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "example_gan_convolutional.py", line 12, in <module>
    from keras_adversarial.image_grid_callback import ImageGridCallback
  File "C:\Users\xxx\Miniconda3\lib\site-packages\keras_adversarial\__init__.py", line 3, in <module>
    from .adversarial_model import AdversarialModel
  File "C:\Users\xxx\Miniconda3\lib\site-packages\keras_adversarial\adversarial_model.py", line 9, in <module>
    from .legacy import keras_2
ModuleNotFoundError: No module named 'keras_adversarial.legacy'

C:\Users\xxx\ML\tyokan_deep\ch04>
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

以上、よろしくお願いいたします。

**Comment by SnowMasaya** [comment]
おそらくjupyter notebookとminicondaで構築したpythonの環境が異なっているため発生しているような気がします。

jupyter notebook上で`! pip freeze`で`keras`のバージョン確認お願いします。
もしバージョンが異なる場合はjupyter notebook上で`! pip install keras==2.1.2`でインストールお願いします。

**Comment by sinjorjob** [comment]
ご回答ありがとうございます。
jupyter notebookのkerasバージョン確認しましたが以下の通り、2.1.2で一致しておりましたので別の原因のようです。。
念のため、jupyter上で「! pip install keras==2.1.2」を実行しましたが、以下の通りすでに導入済み状態でした。

Requirement already satisfied: keras==2.1.2 in c:\users\xxx\miniconda3\lib\site-packages (2.1.2)
Requirement already satisfied: scipy>=0.14 in c:\users\xxx\miniconda3\lib\site-packages (from keras==2.1.2) (1.1.0)
Requirement already satisfied: six>=1.9.0 in c:\users\xxx\miniconda3\lib\site-packages (from keras==2.1.2) (1.11.0)
Requirement already satisfied: numpy>=1.9.1 in c:\xxx\sinfo\miniconda3\lib\site-packages (from keras==2.1.2) (1.14.2)
Requirement already satisfied: pyyaml in c:\xxx\sinfo\miniconda3\lib\site-packages (from keras==2.1.2) (3.13)
In [ ]:

**Comment by icoxfog417** [comment]
[keras-adversarial](https://github.com/bstriner/keras-adversarial/issues/49)本体でも報告があり、まだ解決されていないようです。

一旦`keras_adversarial`をアンインストールし、以下のようにmasterからインストーするするのは試す価値がありそうです(`pip install git+https://github.com/bstriner/keras-adversarial.git`と等価ですが)。

```
git clone https://github.com/bstriner/keras_adversarial.git
cd keras_adversarial
python setup.py install
```

**Comment by sinjorjob** [comment]
ご回答ありがとうございます。
いろいろ試してみましたが、以下の対応を実施したところ解消しました。
-----------------------------------------------------------------------------------------------
AttributeError: 'AdversarialModel' object has no attribute '_feed_output_shapes'
-----------------------------------------------------------------------------------------------
→本家（https://github.com/bstriner/keras-adversarial）のadversarial_model.py でsite-packages\keras_adversarial\adversarial_model.py上書きしたところ本件のエラーが発生しなくなり、
代わりに以下のエラーが発生するようになりました。
-----------------------------------------------------------------------------------------------
ModuleNotFoundError: No module named 'keras_adversarial.legacy'
-----------------------------------------------------------------------------------------------

そこで、Issue「https://github.com/bstriner/keras-adversarial/issues/46」を参考に改め以下の対応を行いました。

anaconda Promptを起動した状態で、以下を実施（上記Issueで記載されている手順）。

pip uninstall keras_adversarial
git clone https://github.com/bstriner/keras_adversarial.git
cd keras_adversarial
python setup.py install

これで解消しました。
問題解消しない時は、Anaconda PromptのDOS画面上ではなく、単純にDOS画面を起動した状態で上記コマンドを実行していた（当方の環境ではパス等が通っているのでAnaconda Prompt上でなくてもコマンドが実行できてしまう状態）点がことなっているので、この点がよろしくなかったようです。
anacondaを入れている環境では、anaconda prompt上(もしくは対象の仮想環境上）で本家Issue46の対応を実施すれば良いということのようです。

お手数おかけしました。

**Comment by icoxfog417** [comment]
解決方法のご連絡をいただきありがとうございました！

対応策をまとめておきます。

* 構築した仮想環境上で実行しているかを確認
* [keras-adversarial #46](https://github.com/bstriner/keras-adversarial/issues/46#issuecomment-372676918)を参考にアンインストール/インストール
