### ISSUE TITLE
Windows10へのQuiverインストール　エラーの件

### ISSUE THREAD

**Issue by t-yoichi0013** [oreilly-japan/deep-learning-with-keras-ja#6]
アナコンダ＋pycharmの環境で、Quiverをインストールしようとしていますが、うまくいきません。
 pip install -r requirements-windows.txtを実行した後の、エラーメッセージは、以下の通りです。
Could not find a version that satisfies the requirement tensorflow==1.8.0 (from -r requirements-windows.txt (line 2))
 (from versions: )

 No matching distribution found for tensorflow==1.8.0 (from -r requirements-windows.txt (line 2))
  
＜環境＞
OS:Windows10(64bit）
Python 3.7.0
pycyarm 2018.3.3
アナコンダのTensorflowのバージョンは、１．１２．０です。

もし、なにか情報がありましたら、教えてください。
以上、よろしくお願いいたします。

**Comment by icoxfog417** [comment]
現在TensorFlowはPython3.7に対応していません( [Python 3.7 compatibility](https://github.com/tensorflow/tensorflow/issues/20517))。また、本書のサンプルコードはPython 3.6を前提に実装されています。

Python 3.6の環境を作成し、改めてセットアップを行ってみてください。
