### ISSUE TITLE
ch07-composite_qa_net.pyのテストデータが利用できない。

### ISSUE THREAD

**Issue by sinjorjob** [oreilly-japan/deep-learning-with-keras-ja#8]
ch07-composite_qa_net.pyのbAbI().downloadメソッド内でダウンロードするファイル「https://s3.amazonaws.com/fair-data/parlai/babi/babi.tar.gz"」 が利用不可状態になっているようで、本テキストのコード(7.4.1)のMemoryNetworkの学習を継続できない状況です。

上記URLにアクセスすると、「This XML file does not appear to have any style information associated with it. The document tree is shown below.」と表示され現在は利用できないようです。

お手数ですが、ご確認をお願いいたします。

**Comment by icoxfog417** [comment]
ご連絡ありがとうございます。修正しました

3180b9c64b2317de1bf0b8441fde914f9926b9a1
